export type Subject = 'math' | 'english' | 'chinese';
export type Grade = '4' | '5' | '6';

export interface QuestionData {
  id: number;
  answer: string;
  abilities: string[];
  scope: string;
}

export const examData: Record<Subject, Record<Grade, QuestionData[]>> = {
  math: {
    '4': [
      { id: 1, answer: 'B', abilities: ['數與運算熟練力', '題意理解與建模解題力'], scope: '計算題' },
      { id: 2, answer: 'B', abilities: ['幾何與量感推理力', '數與運算熟練力'], scope: '圖形題' },
      { id: 3, answer: 'B', abilities: ['數與運算熟練力', '題意理解與建模解題力'], scope: '單位換算題' },
      { id: 4, answer: 'C', abilities: ['數與運算熟練力', '代數化與符號表徵力'], scope: '計算題' },
      { id: 5, answer: 'C', abilities: ['題意理解與建模解題力', '數與運算熟練力'], scope: '多步驟混合題' },
      { id: 6, answer: 'C', abilities: ['題意理解與建模解題力', '資料分析與不確定性理解力'], scope: '情境題' },
      { id: 7, answer: 'A', abilities: ['數與運算熟練力', '題意理解與建模解題力'], scope: '單位換算題' },
      { id: 8, answer: 'C', abilities: ['代數化與符號表徵力', '題意理解與建模解題力'], scope: '找規律題' },
      { id: 9, answer: 'A', abilities: ['題意理解與建模解題力', '數與運算熟練力'], scope: '情境題' },
      { id: 10, answer: 'A', abilities: ['代數化與符號表徵力', '資料分析與不確定性理解力'], scope: '找規律題' },
      { id: 11, answer: 'C', abilities: ['幾何與量感推理力', '題意理解與建模解題力'], scope: '圖形題' },
      { id: 12, answer: 'B', abilities: ['資料分析與不確定性理解力', '代數化與符號表徵力'], scope: '平均數與中位數' },
      { id: 13, answer: 'A', abilities: ['幾何與量感推理力', '數與運算熟練力'], scope: '圖形題' },
      { id: 14, answer: 'C', abilities: ['數與運算熟練力', '題意理解與建模解題力'], scope: '計算題' },
      { id: 15, answer: 'C', abilities: ['幾何與量感推理力', '題意理解與建模解題力'], scope: '面積體積比較' },
    ],
    '5': [
      { id: 1, answer: 'B', abilities: ['數與運算熟練力', '代數化與符號表徵力'], scope: '計算題' },
      { id: 2, answer: 'A', abilities: ['數與運算熟練力', '代數化與符號表徵力'], scope: '計算題' },
      { id: 3, answer: 'B', abilities: ['數與運算熟練力', '題意理解與建模解題力'], scope: '應用題' },
      { id: 4, answer: 'A', abilities: ['幾何與量感推理力', '代數化與符號表徵力'], scope: '圖形題' },
      { id: 5, answer: 'C', abilities: ['數與運算熟練力', '題意理解與建模解題力'], scope: '單位換算題' },
      { id: 6, answer: 'A', abilities: ['題意理解與建模解題力', '數與運算熟練力'], scope: '多步驟混合題' },
      { id: 7, answer: 'B', abilities: ['代數化與符號表徵力', '資料分析與不確定性理解力'], scope: '列式題' },
      { id: 8, answer: 'C', abilities: ['數與運算熟練力', '代數化與符號表徵力'], scope: '應用題' },
      { id: 9, answer: 'C', abilities: ['題意理解與建模解題力', '數與運算熟練力'], scope: '多步驟混合題' },
      { id: 10, answer: 'C', abilities: ['資料分析與不確定性理解力', '題意理解與建模解題力'], scope: '平均數與中位數' },
      { id: 11, answer: 'A', abilities: ['代數化與符號表徵力', '題意理解與建模解題力'], scope: '列式題' },
      { id: 12, answer: 'A', abilities: ['幾何與量感推理力', '資料分析與不確定性理解力'], scope: '圖形題' },
      { id: 13, answer: 'A', abilities: ['幾何與量感推理力', '資料分析與不確定性理解力'], scope: '角度推理' },
      { id: 14, answer: 'C', abilities: ['代數化與符號表徵力', '幾何與量感推理力'], scope: '找規律題' },
      { id: 15, answer: 'C', abilities: ['數與運算熟練力', '代數化與符號表徵力'], scope: '應用題' },
    ],
    '6': [
      { id: 1, answer: 'B', abilities: ['代數化與符號表徵力', '數與運算熟練力'], scope: '一元一次方程式雛形' },
      { id: 2, answer: 'B', abilities: ['代數化與符號表徵力', '資料分析與不確定性理解力'], scope: '找規律題' },
      { id: 3, answer: 'B', abilities: ['數與運算熟練力', '資料分析與不確定性理解力'], scope: '應用題' },
      { id: 4, answer: 'B', abilities: ['幾何與量感推理力', '題意理解與建模解題力'], scope: '圖形題' },
      { id: 5, answer: 'B', abilities: ['數與運算熟練力', '資料分析與不確定性理解力'], scope: '估算題' },
      { id: 6, answer: 'C', abilities: ['資料分析與不確定性理解力', '題意理解與建模解題力'], scope: '平均數與中位數' },
      { id: 7, answer: 'B', abilities: ['題意理解與建模解題力', '數與運算熟練力'], scope: '多步驟混合題' },
      { id: 8, answer: 'C', abilities: ['幾何與量感推理力', '題意理解與建模解題力'], scope: '圖形題' },
      { id: 9, answer: 'B', abilities: ['數與運算熟練力', '題意理解與建模解題力'], scope: '應用題' },
      { id: 10, answer: 'B', abilities: ['題意理解與建模解題力', '資料分析與不確定性理解力'], scope: '情境題' },
      { id: 11, answer: 'C', abilities: ['數與運算熟練力', '代數化與符號表徵力'], scope: '應用題' },
      { id: 12, answer: 'C', abilities: ['代數化與符號表徵力', '題意理解與建模解題力'], scope: '列式題' },
      { id: 13, answer: 'A', abilities: ['代數化與符號表徵力', '題意理解與建模解題力'], scope: '列式題' },
      { id: 14, answer: 'C', abilities: ['幾何與量感推理力', '代數化與符號表徵力'], scope: '面積體積比較' },
      { id: 15, answer: 'C', abilities: ['數與運算熟練力', '代數化與符號表徵力'], scope: '計算題' },
    ]
  },
  english: {
    '4': [
      { id: 1, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 2, answer: 'A', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 3, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 4, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 5, answer: 'A', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 6, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 7, answer: 'B', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 8, answer: 'B', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 9, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 10, answer: 'A', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 11, answer: 'B', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 12, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 13, answer: 'A', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 14, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 15, answer: 'C', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 16, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 17, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 18, answer: 'A', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 19, answer: 'C', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 20, answer: 'D', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 21, answer: 'B', abilities: ['閱讀理解力'], scope: '閱讀理解' },
      { id: 22, answer: 'C', abilities: ['閱讀理解力'], scope: '閱讀理解' },
      { id: 23, answer: 'D', abilities: ['閱讀理解力'], scope: '閱讀理解' },
    ],
    '5': [
      { id: 1, answer: 'C', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 2, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 3, answer: 'C', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 4, answer: 'A', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 5, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 6, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 7, answer: 'D', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 8, answer: 'C', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 9, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 10, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 11, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 12, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 13, answer: 'A', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 14, answer: 'B', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 15, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 16, answer: 'D', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 17, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 18, answer: 'A', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 19, answer: 'B', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 20, answer: 'B', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 21, answer: 'B', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 22, answer: 'A', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 23, answer: 'C', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 24, answer: 'A', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 25, answer: 'B', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 26, answer: 'C', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 27, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 28, answer: 'A', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 29, answer: 'A', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 30, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 31, answer: 'D', abilities: ['閱讀理解力'], scope: '閱讀理解' },
      { id: 32, answer: 'B', abilities: ['閱讀理解力'], scope: '閱讀理解' },
      { id: 33, answer: 'C', abilities: ['閱讀理解力'], scope: '閱讀理解' },
    ],
    '6': [
      { id: 1, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 2, answer: 'A', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 3, answer: 'C', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 4, answer: 'D', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 5, answer: 'D', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 6, answer: 'A', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 7, answer: 'C', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 8, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 9, answer: 'C', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 10, answer: 'B', abilities: ['字彙與片語運用力'], scope: '基本單字' },
      { id: 11, answer: 'B', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 12, answer: 'D', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 13, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 14, answer: 'B', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 15, answer: 'B', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 16, answer: 'C', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 17, answer: 'B', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 18, answer: 'D', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 19, answer: 'A', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 20, answer: 'A', abilities: ['語法精準力'], scope: '文法概念' },
      { id: 21, answer: 'C', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 22, answer: 'A', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 23, answer: 'D', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 24, answer: 'B', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 25, answer: 'C', abilities: ['引導式書寫力'], scope: '文法概念' },
      { id: 26, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 27, answer: 'A', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 28, answer: 'C', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 29, answer: 'C', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 30, answer: 'B', abilities: ['情境溝通力'], scope: '句意邏輯' },
      { id: 31, answer: 'B', abilities: ['閱讀理解力'], scope: '閱讀理解' },
      { id: 32, answer: 'C', abilities: ['閱讀理解力'], scope: '閱讀理解' },
      { id: 33, answer: 'D', abilities: ['閱讀理解力'], scope: '閱讀理解' },
    ]
  },
  chinese: {
    '4': [
      { id: 1, answer: 'A', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 2, answer: 'B', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 3, answer: 'C', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 4, answer: 'D', abilities: ['語文分析力'], scope: '語句邏輯' },
      { id: 5, answer: 'C', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 6, answer: 'B', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 7, answer: 'C', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 8, answer: 'B', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 9, answer: 'A', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 10, answer: 'D', abilities: ['多元整合力'], scope: '跨領域閱讀' },
      { id: 11, answer: 'A', abilities: ['多元整合力'], scope: '跨領域閱讀' },
      { id: 12, answer: 'A', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 13, answer: 'B', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 14, answer: 'C', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 15, answer: 'A', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 16, answer: 'A', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 17, answer: 'D', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 18, answer: 'D', abilities: ['多元整合力'], scope: '跨領域閱讀' },
      { id: 19, answer: 'C', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 20, answer: 'A', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 21, answer: 'B', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 22, answer: 'C', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 23, answer: 'A', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 24, answer: 'C', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 25, answer: 'B', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 26, answer: 'B', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 27, answer: 'A', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 28, answer: 'D', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 29, answer: 'B', abilities: ['多元整合力'], scope: '跨領域閱讀' },
      { id: 30, answer: 'D', abilities: ['多元整合力'], scope: '跨領域閱讀' },
    ],
    '5': [
      { id: 1, answer: 'A', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 2, answer: 'A', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 3, answer: 'A', abilities: ['語文分析力'], scope: '文意理解' },
      { id: 4, answer: 'D', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 5, answer: 'C', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 6, answer: 'A', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 7, answer: 'A', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 8, answer: 'A', abilities: ['語文分析力'], scope: '語句邏輯' },
      { id: 9, answer: 'D', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 10, answer: 'B', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 11, answer: 'D', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 12, answer: 'C', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 13, answer: 'A', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 14, answer: 'A', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 15, answer: 'C', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 16, answer: 'D', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 17, answer: 'B', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 18, answer: 'C', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 19, answer: 'C', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 20, answer: 'B', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 21, answer: 'C', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 22, answer: 'D', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 23, answer: 'A', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 24, answer: 'B', abilities: ['多元整合力'], scope: '文白閱讀' },
      { id: 25, answer: 'D', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 26, answer: 'A', abilities: ['多元整合力'], scope: '文白閱讀' },
      { id: 27, answer: 'D', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 28, answer: 'B', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 29, answer: 'B', abilities: ['多元整合力'], scope: '文白閱讀' },
      { id: 30, answer: 'C', abilities: ['語文分析力'], scope: '語文應用' },
    ],
    '6': [
      { id: 1, answer: 'D', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 2, answer: 'C', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 3, answer: 'A', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 4, answer: 'A', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 5, answer: 'D', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 6, answer: 'B', abilities: ['語文分析力'], scope: '語文應用' },
      { id: 7, answer: 'B', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 8, answer: 'A', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 9, answer: 'B', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 10, answer: 'D', abilities: ['文化知識力'], scope: '文學常識' },
      { id: 11, answer: 'D', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 12, answer: 'A', abilities: ['文章分析力'], scope: '文意理解' },
      { id: 13, answer: 'C', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 14, answer: 'A', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 15, answer: 'A', abilities: ['語文分析力'], scope: '語句邏輯' },
      { id: 16, answer: 'C', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 17, answer: 'B', abilities: ['文化知識力'], scope: '文意理解' },
      { id: 18, answer: 'A', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 19, answer: 'D', abilities: ['基礎知識力'], scope: '語文應用' },
      { id: 20, answer: 'C', abilities: ['基礎知識力'], scope: '字音、字形' },
      { id: 21, answer: 'A', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 22, answer: 'D', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 23, answer: 'B', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 24, answer: 'B', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 25, answer: 'A', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 26, answer: 'B', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 27, answer: 'D', abilities: ['文章分析力'], scope: '文白閱讀' },
      { id: 28, answer: 'A', abilities: ['多元整合力'], scope: '跨領域閱讀' },
      { id: 29, answer: 'B', abilities: ['多元整合力'], scope: '跨領域閱讀' },
      { id: 30, answer: 'C', abilities: ['多元整合力'], scope: '跨領域閱讀' },
    ]
  }
};

export const abilityDescriptions: Record<string, string> = {
  '數與運算熟練力': '四則計算正確；能用估算檢核；分數小數、比例不混淆；因倍數合理使用。',
  '代數化與符號表徵力': '能設定未知數並列式；能由式子推演情境；能推理問題規律。',
  '題意理解與建模解題力': '能抓取條件與問題並選擇合理策略；能處理隱含條件並正確作答。',
  '幾何與量感推理力': '能讀圖並作輔助線；量感合理；公式使用正確且了解適用條件。',
  '資料分析與不確定性理解力': '能正確讀圖與換算；能判斷平均數是否受極端值影響。',
  '邏輯推理力': '利用推論尋找線索，具備思辨與判斷能力。',
  '字彙與片語運用力': '能依上下文選出適當字彙；具備固定搭配辨識力；能依句型辨識正確詞性。',
  '語法精準力': '能精確變換動詞時態；維持主動詞一致；正確運用特殊句型且語序正確。',
  '閱讀理解力': '能歸納主旨排除干擾；具備語意轉譯能力；能從文本提取證據進行推論。',
  '情境溝通力': '能辨識溝通目的並適當回應；理解前後文意，並正確使用連接詞。',
  '引導式書寫力': '文法精確(時態/單複數)；詞彙搭配自然且拼寫正確；句構完整。',
  '基礎知識力': '形音義成語、詞性、工具書和標點符號的基礎能力。',
  '文章分析力': '文言文、韻文或現代文學的理解能力（文意理解、文章分析、篇章結構）。',
  '語文分析力': '句型邏輯思考，修辭理解分析與語氣判讀思辨能力。',
  '多元整合力': '跨領域、跨學科整合生活文類以各及類型文體的解讀能力。',
  '文化知識力': '國學與文化常識內涵考題，測驗學生文化內涵的能力向度。'
};
